sudo: required

language: node_js

services: mongodb

before_script:
  - sleep 10 # because mongodb doesn't start accepting connections right away
  - mongo test_db --eval 'db.createUser({user:"test",pwd:"test",roles:["readWrite"]});'

node_js:
  - '8'

env:
  - TEST_DB_URI=mongodb://test:test@127.0.0.1:27017/test_db

matrix:
  include:
    - node_js: '10'
  allow_failures:
    - node_js: '10'

notifications:
  disabled: true

before_install:
  - npm install -g codecov

install:
  - npm install

script:
  - node index.js &
  - npm run check-coverage
  - codecov

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
