sudo: required

language: node_js

node_js:
  - '8'

? env
matrix:
  include:
    - node_js: '10'
  allow_failures:
    - node_js: '10'

notifications:
  disabled: true

before_install:
  - npm install -g codecov

install:
  - npm install

script:
  - node index.js &
  - npm run check-coverage
  - codecov

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
